export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  confirm: "/confirm",
  resetPassword: "/reset-password",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  nutrition: "/nutrition",
  nutritionAdd: "/nutrition/add",
  nutritionHistory: "/nutrition/history",
  training: "/training",
  trainingStart: "/training/start",
  trainingPrograms: "/training/programs",
  stats: "/stats",
  habits: "/habits",
  coach: "/coach",
  profile: "/profile",
} as const;
